# Прочитать всех клиентов
GET http://localhost:8080/clients/all
Authorization: Basic eGFuOnBhc3M=

###

# Создание клиента
POST http://localhost:8080/clients/create
Content-Type: application/json; charset=utf-8;


 {
    "name": "ООО Моя компашка",
    "inn": "111111",
    "ogrn": "222222"
 }
###

# Создание клиента
POST http://localhost:8080/clients/create
Content-Type: application/json; charset=utf-8;


 {
    "name": "ООО Моя 32",
    "inn": "112223",
    "ogrn": "33333"
 }
###

# Прочитать клиента с ID 1
GET http://localhost:8080/clients/4
Authorization: Basic eGFuOnBhc3M=

###


# Удалить клиента
DELETE http://localhost:8080/clients/delete/5

###