# Прочитать все
GET http://localhost:8080/documents/all
Authorization: Basic eGFuOnBhc3M=

###

# Создание документа
POST http://localhost:8080/documents/create
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic eGFuOnBhc3M=

--WebAppBoundary
Content-Disposition: form-data; name="document"
Content-Type: application/json; charset=utf-8;

 {
    "docNumber": "123",
    "docDate": "2111-11-02",
    "clientId": 4,
    "userId": 1

 }

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sample.dat"

< D:/intel-lan/log/22.txt
--WebAppBoundary--

###

# Прочитать
GET http://localhost:8080/documents/5
Authorization: Basic eGFuOnBhc3M=

###

# Удалить документ
DELETE http://localhost:8080/documents/5
Authorization: Basic eGFuOnBhc3M=

###


