# Прочитать всех клиентов
GET http://localhost:8080/users/all
Content-Type: application/json; charset=utf-8;
Authorization: Basic eGFuOnBhc3M=

###

# Создание пользователя
POST http://localhost:8080/users/create
Content-Type: application/json; charset=utf-8;

{
  "username": "New1",
  "password": "pass",
  "fullName": "Moe polnoe imya1"
}

####  Создание пользователя 2
POST http://localhost:8080/users/create
Content-Type: application/json; charset=utf-8;

{
  "username": "Из запроса2",
  "password": "PassOdered2",
  "fullName": "Moe polnoe imya22"
}

###

#получения по id
GET http://localhost:8080/users/read/2
Authorization: Basic eGFuOnBhc3M=

###


# Получение списка документов, размещённых пользователем
GET http://localhost:8080/users/1/documents
Authorization: Basic eGFuOnBhc3M=

###


#Получение информации о текущем пользователе
GET http://localhost:8080/users/profile
Authorization: Basic eGFuOnBhc3M=

###


# Дополнительные запросы
# Проверка взятия документов - создали клиента
POST http://localhost:8080/clients/create
Content-Type: application/json; charset=utf-8;
Authorization: Basic eGFuOnBhc3M=


{
  "name": "ООО Моя 22",
  "inn": "112222",
  "ogrn": "33333"
}

###

# Создание документа
POST http://localhost:8080/documents/create
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic eGFuOnBhc3M=

--WebAppBoundary
Content-Disposition: form-data; name="document"
Content-Type: application/json; charset=utf-8;

 {
    "docnumber": "123",
    "docDate": "2111-11-02",
    "clientId": 3,
    "userId": 1

 }

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sample.dat"

< D:/intel-lan/log/setupapi.dev.20121022_125727.log
--WebAppBoundary--

###

